version: "3.0"

services:
  redis:
    image: redis:alpine
    command: redis-server --port 6379 --dir /data
    container_name: redis
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
    volumes:
      - /home/ec2-user/redis/data:/data
    restart: always
